version: "2"

services:
  fabmodules:
    build: .
    image: fabmodules
    container_name: fabmodules
    ports:
      - 12345:9090

networks:
    default:
        external:
            name: nginx_default
